=== ranaictiu/SP-JS-ProvisioningEngine/PnP Provision/AddIn/Items/Templates/pnp-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Language": { "type": "integer" },
    "TimeZone": { "type": "integer" },
    "Description": { "type": "string" },
    "UseSamePermissionsAsParentSite": { "type": "boolean" },
    "WebTemplateId": { "type": "string" },
    "Templates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Description": { "type": "string" },
          "Security": {
            "type": "object",
            "properties": {
              "AdditionalAdministrators": {
                "type": "array",
                "items": {}
              },
              "AdditionalOwners": {
                "type": "array",
                "items": {}
              },
              "AdditionalMembers": {
                "type": "array",
                "items": {}
              },
              "AdditionalVisitors": {
                "type": "array",
                "items": {}
              },
              "SiteGroups": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "Members": {
                      "type": "array",
                      "items": {}
                    },
                    "Title": {
                      "type": "string"
                    },
                    "Description": {
                      "type": "string"
                    },
                    "Owner": {
                      "type": "string"
                    },
                    "AllowMembersEditMembership": {
                      "type": "boolean"
                    },
                    "AllowRequestToJoinLeave": {
                      "type": "boolean"
                    },
                    "AutoAcceptRequestToJoinLeave": {
                      "type": "boolean"
                    },
                    "OnlyAllowMembersViewMembership": {
                      "type": "boolean"
                    },
                    "RequestToJoinLeaveEmailSetting": {
                      "type": "null"
                    }
                  },
                  "required": [
                    "Members",
                    "Title",
                    "Description",
                    "Owner",
                    "AllowMembersEditMembership",
                    "AllowRequestToJoinLeave",
                    "AutoAcceptRequestToJoinLeave",
                    "OnlyAllowMembersViewMembership",
                    "RequestToJoinLeaveEmailSetting"
                  ]
                }
              },
              "SiteSecurityPermissions": {
                "type": "object",
                "properties": {
                  "RoleDefinitions": {
                    "type": "array",
                    "items": {}
                  },
                  "RoleAssignments": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "Principal": {
                          "type": "string"
                        },
                        "RoleDefinition": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "Principal",
                        "RoleDefinition"
                      ]
                    }
                  }
                },
                "required": [
                  "RoleDefinitions",
                  "RoleAssignments"
                ]
              }
            }
          },
          "SiteFields": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ID": { "type": "string" },
                "Name": { "type": "string" },
                "DisplayName": { "type": "string" },
                "Group": { "type": "string" },
                "Type": { "type": "string" },
                "List": { "type": "string" },
                "ShowField": { "type": "string" },
                "JSLink": { "type": "string" },
                "Xml": { "type": "string" }
              },
              "required": [ "ID", "Name" ]
            }
          },
          "ContentTypes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ParentId": { "type": "string" },
                "Name": { "type": "string" },
                "Group": { "type": "string" },
                "Description": { "type": "string" },
                "FieldRefs": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "ID": { "type": "string" },
                      "Name": { "type": "string" },
                      "Required": { "type": "boolean" }
                    },
                    "required": [ "ID", "Name" ]
                  }
                },
                "DocumentSetTemplate": {
                  "type": "object",
                  "properties": {
                    "AllowedContentTypes": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "Name": { "type": "string" },
                          "Description": { "type": "string" }
                        },
                        "required": [ "Name", "Description" ]
                      }
                    },
                    "SharedFields": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "ID": { "type": "string" },
                          "Name": { "type": "string" }
                        },
                        "required": [ "ID", "Name" ]
                      }
                    },
                    "WelcomePageFields": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "ID": { "type": "string" },
                          "Name": { "type": "string" }
                        },
                        "required": [ "ID", "Name" ]
                      }
                    }
                  },
                  "required": [ "AllowedContentTypes", "SharedFields", "WelcomePageFields" ]
                }
              },
              "required": [ "ParentId", "Name", "Group", "Description", "FieldRefs" ]
            }
          },
          "Lists": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Title": { "type": "string" },
                "Description": { "type": "string" },
                "DocumentTemplate": { "type": "null" },
                "OnQuickLaunch": { "type": "boolean" },
                "TemplateType": { "type": "integer" },
                "Url": { "type": "string" },
                "EnableVersioning": { "type": "boolean" },
                "EnableMinorVersions": { "type": "boolean" },
                "DraftVersionVisibility": { "type": "integer" },
                "EnableModeration": { "type": "boolean" },
                "MinorVersionLimit": { "type": "integer" },
                "MaxVersionLimit": { "type": "integer" },
                "ForceCheckOut": { "type": "boolean" },
                "RemoveExistingContentTypes": { "type": "boolean" },
                "ContentTypesEnabled": { "type": "boolean" },
                "Hidden": { "type": "boolean" },
                "EnableFolderCreation": { "type": "boolean" },
                "ContentTypeBindings": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "Name": { "type": "string" },
                      "Default": { "type": "boolean" },
                      "Hidden": { "type": "boolean" }
                    },
                    "required": [ "Name", "Default" ]
                  }
                },
                "RemoveExistingViews": { "type": "boolean" },
                "Views": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "DisplayName": { "type": "string" },
                      "DefaultView": { "type": "boolean" },
                      "Type": { "type": "string" },
                      "Paged": { "type": "boolean" },
                      "RowLimit": { "type": "integer" },
                      "Query": { "type": "string" },
                      "ViewFields": {
                        "type": "array",
                        "items": { "type": "string" }
                      }
                    },
                    "required": [ "DisplayName", "DefaultView", "Type", "Paged", "RowLimit", "Query", "ViewFields" ]
                  }
                }
              },
              "required": [ "Title", "Description", "Url" ]
            }
          },
          "CustomActions": {
            "type": "object",
            "properties": {
              "SiteCustomActions": {
                "type": "array",
                "items": {}
              },
              "WebCustomActions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "Name": { "type": "string" },
                    "Description": { "type": "string" },
                    "Sequence": { "type": "integer" },
                    "Location": { "type": "string" },
                    "ScriptSrc": { "type": "string" },
                    "Group": { "type": "string" },
                    "Rights": { "type": "string" },
                    "Url": { "type": "string" },
                    "CommandUIExtension": {
                      "type": "object",
                      "properties": {
                        "Url": { "type": "string" },
                        "Xml": { "type": "string" }
                      },
                      "required": [ "Url" ]
                    }
                  },
                  "required": [ "Name" ]
                }
              }
            },
            "required": [ "SiteCustomActions", "WebCustomActions" ]
          },
          "Workflows": {
            "type": "object",
            "properties": {
              "WorkflowSubscriptions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "DefinitionId": { "type": "string" },
                    "Name": { "type": "string" },
                    "Enabled": { "type": "boolean" },
                    "WorkflowStartEvent": { "type": "boolean" },
                    "TaskList": { "type": "string" },
                    "HistoryList": { "type": "string" }
                  },
                  "required": [ "DefinitionId", "Name", "Enabled", "WorkflowStartEvent", "TaskList", "HistoryList" ]
                }
              }
            },
            "required": [ "WorkflowSubscriptions" ]
          },
          "Pages": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Title": { "type": "string" },
                "SEOTitle": { "type": "string" },
                "Layout": { "type": "string" },
                "Url": { "type": "string" },
                "Overwrite": { "type": "boolean" },
                "Security": {
                  "type": "object",
                  "properties": {
                    "BreakRoleInheritance": {
                      "type": "object",
                      "properties": {
                        "ClearSubscopes": { "type": "boolean" },
                        "CopyRoleAssignments": { "type": "boolean" },
                        "RoleAssignment": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "Principal": { "type": "string" },
                              "RoleDefinition": { "type": "string" }
                            },
                            "required": [ "Principal", "RoleDefinition" ]
                          }
                        }
                      },
                      "required": [ "ClearSubscopes", "CopyRoleAssignments", "RoleAssignment" ]
                    }
                  },
                  "required": [ "BreakRoleInheritance" ]
                }
              },
              "required": [ "Title", "SEOTitle", "Layout", "Url", "Overwrite" ]
            }
          },
          "Navigation": {
            "type": "object",
            "properties": {
              "GlobalNavigation": {
                "type": "object",
                "properties": {
                  "NavigationType": { "type": "string" },
                  "ManagedNavigation": { "type": "null" },
                  "StructuralNavigation": { "type": "null" }
                },
                "required": [ "NavigationType", "ManagedNavigation", "StructuralNavigation" ]
              },
              "CurrentNavigation": {
                "type": "object",
                "properties": {
                  "NavigationType": { "type": "string" },
                  "ManagedNavigation": {
                    "anyOf": [
                      { "type": "null" },
                      { "type": "object" }
                    ]
                  },
                  "StructuralNavigation": {
                    "anyOf": [
                      { "type": "null" },
                      { "type": "object" }
                    ],
                    "properties": {
                      "RemoveExistingNodes": { "type": "boolean" },
                      "ShowPages": { "type": "boolean" },
                      "NavigationNode": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "Title": { "type": "string" },
                            "IsExternal": { "type": "boolean" },
                            "Url": { "type": "string" }
                          },
                          "required": [ "Title", "IsExternal", "Url" ]
                        }
                      }
                    },
                    "required": [ "RemoveExistingNodes", "ShowPages", "NavigationNode" ]
                  }
                },
                "required": [ "NavigationType", "ManagedNavigation", "StructuralNavigation" ]
              }
            },
            "required": [ "GlobalNavigation", "CurrentNavigation" ]
          },
          "WebSettings": {
            "type": "object",
            "properties": { "WelcomePage": { "type": "string" } },
            "required": [ "WelcomePage" ]
          }
        },
        "required": [ "Description" ]
      }
    }
  },
  "required": [ "Templates" ]
}

=== ranaictiu/SP-JS-ProvisioningEngine/PnP Provision/AddIn/Items/Templates/2STWithColsCTsViews.json
{
  "$schema": "./pnp-schema.json",
  "Language": 1033,
  "UseSamePermissionsAsParentSite": false,
  "WebTemplateId": "STS#0",
  "Description": "Basic site template with site columns (lookup) and content type, views",
  "Templates": [
    {
      "Description": "Create Lists first",
      "Security": {
        "AdditionalOwners": [],
        "SiteGroups": [
          {
            "Members": [],
            "Title": "{{SiteTitle}} Owners",
            "Description": "Full control to the site",
            "Owner": "",
            "AllowMembersEditMembership": false,
            "AllowRequestToJoinLeave": false,
            "AutoAcceptRequestToJoinLeave": false,
            "OnlyAllowMembersViewMembership": false,
            "RequestToJoinLeaveEmailSetting": null
          },
          {
            "Members": [],
            "Title": "{{SiteTitle}} Contributors",
            "Description": "Can view, add, update, and delete list items and documents",
            "Owner": "",
            "AllowMembersEditMembership": false,
            "AllowRequestToJoinLeave": false,
            "AutoAcceptRequestToJoinLeave": false,
            "OnlyAllowMembersViewMembership": false,
            "RequestToJoinLeaveEmailSetting": null
          },
          {
            "Members": [],
            "Title": "{{SiteTitle}} Visitors",
            "Description": "Can read and view documents",
            "Owner": "",
            "AllowMembersEditMembership": false,
            "AllowRequestToJoinLeave": false,
            "AutoAcceptRequestToJoinLeave": false,
            "OnlyAllowMembersViewMembership": false,
            "RequestToJoinLeaveEmailSetting": null
          }
        ],
        "SiteSecurityPermissions": {
          "RoleDefinitions": [],
          "RoleAssignments": [
            {
              "Principal": "{{SiteTitle}} Owners",
              "RoleDefinition": "Full Control"
            },
            {
              "Principal": "{{SiteTitle}} Contributors",
              "RoleDefinition": "Contribute"
            },
            {
              "Principal": "{{SiteTitle}} Visitors",
              "RoleDefinition": "View Only"
            }
          ]
        }
      },
      "Features": {
        "SiteFeatures": [],
        "WebFeatures": [
          {
            "ID": "94c94ca6-b32f-4da9-a9e3-1f3d343d7ecb",
            "Description": "SharePoint Server Publishing",
            "Deactivate": false
          },
          {
            "ID": "ec918931-c874-4033-bd09-4f36b2e31fef",
            "Description": "Workflows can use app permissions",
            "Deactivate": false
          },
          {
            "ID": "57311b7a-9afd-4ff0-866e-9393ad6647b1",
            "Description": "Workflow Task Content Type",
            "Deactivate": false
          },
          {
            "ID": "7201d6a4-a5d3-49a1-8c19-19c4bac6e668",
            "Description": "Metadata Navigation and Filtering",
            "Deactivate": false
          }
        ]
      },
      "SiteFields": [
        {
          "ID": "{FA0ADB68-C7F3-4BF0-8AB8-1766EE441C03}",
          "Name": "ProvisioningAppBasicDesc",
          "DisplayName": "PA Description",
          "Group": "ProvisioningApp",
          "Type": "Text"
        }
      ],
      "ContentTypes": [
        {
          "Name": "PA Basic Parent",
          "ParentId": "0x01",
          "Group": "ProvisioningApp",
          "Description": "Provisioning App Basic Parent Content Type",
          "FieldRefs": [
            {
              "ID": "{fa564e0f-0c70-4ab9-b863-0177e6ddd247}",
              "Name": "Title",
              "Required": true
            },
            {
              "Name": "ProvisioningAppBasicDesc",
              "ID": "{FA0ADB68-C7F3-4BF0-8AB8-1766EE441C03}",
              "Required": false
            }
          ]
        }
      ],
      "Lists": [
        {
          "Title": "Parent List",
          "Url": "Lists/ParentList",
          "Description": "Parent List",
          "TemplateType": 100,
          "OnQuickLaunch": false,
          "DraftVersionVisibility": 0,
          "EnableAttachments": true,
          "EnableFolderCreation": true,
          "EnableMinorVersions": false,
          "EnableModeration": false,
          "EnableVersioning": false,
          "ForceCheckOut": false,
          "Hidden": false,
          "MaxVersionLimit": 0,
          "MinorVersionLimit": 0,
          "RemoveExistingContentTypes": true,
          "RemoveExistingViews": true,
          "ContentTypesEnabled": true,
          "ContentTypeBindings": [
            {
              "Name": "PA Basic Parent",
              "Default": true
            }
          ],
          "Views": [
            {
              "DisplayName": "All Parent Items",
              "DefaultView": true,
              "Type": "HTML",
              "Paged": true,
              "RowLimit": 50,
              "Query": "<OrderBy><FieldRef Name=\"ID\" /></OrderBy>",
              "ViewFields": [ "LinkTitleNoMenu", "ProvisioningAppBasicDesc" ]
            }
          ]
        },
        {
          "Title": "Child List",
          "Description": "Child List",
          "OnQuickLaunch": false,
          "TemplateType": 100,
          "Url": "Lists/ChildList",
          "EnableVersioning": false,
          "EnableMinorVersions": false,
          "DraftVersionVisibility": 0,
          "EnableModeration": false,
          "MinorVersionLimit": 0,
          "MaxVersionLimit": 0,
          "ForceCheckOut": false,
          "RemoveExistingContentTypes": false,
          "RemoveExistingViews": false,
          "ContentTypesEnabled": true,
          "Hidden": false,
          "EnableAttachments": true,
          "EnableFolderCreation": true
        }
      ]
    },
    {
      "Description": "Creating lookup fields/content types based on previous template",
      "SiteFields": [
        {
          "ID": "{858F131E-0C95-4F86-8B80-DAFCEEC4DE97}",
          "Name": "ProvisionAppBasicLookup",
          "DisplayName": "Parent",
          "Group": "ProvisioningApp",
          "Type": "Lookup",
          "List": "Lists/ParentList",
          "Required": true,
          "ShowField": "Title"
        }
      ],
      "ContentTypes": [
        {
          "Description": "Content Type with lookup field",
          "Name": "PA Basic Child",
          "ParentId": "0x01",
          "Group": "ProvisioningApp",
          "FieldRefs": [
            {
              "ID": "fa564e0f-0c70-4ab9-b863-0177e6ddd247",
              "Name": "Title",
              "DisplayName": "New Title"
            },
            {
              "ID": "bc91a437-52e7-49e1-8c4e-4698904b2b6d",
              "Name": "LinkTitle",
              "DisplayName": "New Title"
            },
            {
              "ID": "82642ec8-ef9b-478f-acf9-31f7d45fbc31",
              "Name": "LinkTitleNoMenu",
              "DisplayName": "New Title"
            },
            {
              "ID": "{858F131E-0C95-4F86-8B80-DAFCEEC4DE97}",
              "Name": "ProvisionAppBasicLookup",
              "Required": true
            }
          ]
        }
      ],
      "Lists": [
        {
          "Title": "Child List",
          "Description": "Child List",
          "Url": "Lists/ChildList",
          "ContentTypesEnabled": true,
          "RemoveExistingContentTypes": true,
          "ContentTypeBindings": [
            {
              "Name": "PA Basic Child",
              "Default": true
            }
          ]
        }
      ]
    }
  ]
}
